'use client';

import { motion } from 'framer-motion';
import { Award, BookOpen, TrendingUp, Download } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { gradeScale } from '@/lib/db';

interface SubjectData {
  courseName: string;
  credits: number;
  grade: string;
}

interface ResultsCardProps {
  sgpa: number;
  totalCredits: number;
  totalQualityPoints: number;
  subjects: SubjectData[];
}

export default function ResultsCard({
  sgpa,
  totalCredits,
  totalQualityPoints,
  subjects,
}: ResultsCardProps) {
  const getGradeColor = (sgpa: number) => {
    if (sgpa >= 9) return 'text-emerald-600 dark:text-emerald-400';
    if (sgpa >= 8) return 'text-green-600 dark:text-green-400';
    if (sgpa >= 7) return 'text-lime-600 dark:text-lime-400';
    if (sgpa >= 6) return 'text-yellow-600 dark:text-yellow-400';
    if (sgpa >= 5) return 'text-orange-600 dark:text-orange-400';
    return 'text-red-600 dark:text-red-400';
  };

  const getPerformanceText = (sgpa: number) => {
    if (sgpa >= 9) return 'Outstanding Performance!';
    if (sgpa >= 8) return 'Excellent Work!';
    if (sgpa >= 7) return 'Very Good!';
    if (sgpa >= 6) return 'Good Progress';
    if (sgpa >= 5) return 'Average Performance';
    return 'Needs Improvement';
  };

  const generatePDF = () => {
    const doc = new jsPDF();
    
    // Add title
    doc.setFontSize(22);
    doc.setTextColor(44, 53, 64); // rv-navy
    doc.text('SGPA Result Report', 14, 22);
    
    doc.setFontSize(11);
    doc.setTextColor(100);
    doc.text(`Generated on: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`, 14, 32);

    // Summary Box
    doc.setFillColor(74, 124, 89); // rv-green
    doc.roundedRect(14, 40, 182, 35, 3, 3, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(14);
    doc.text('Semester Performance Summary', 20, 52);
    
    doc.setFontSize(12);
    doc.text(`SGPA: ${sgpa.toFixed(2)}`, 20, 65);
    doc.text(`Total Credits: ${totalCredits.toFixed(1)}`, 80, 65);
    doc.text(`Total Quality Points: ${totalQualityPoints.toFixed(2)}`, 140, 65);
    
    // Subjects Table
    const tableData = subjects
      .filter(s => s.courseName && s.grade)
      .map(s => {
        const gradeValue = gradeScale[s.grade] || 0;
        const qualityPoints = s.credits * gradeValue;
        return [
          s.courseName,
          s.credits.toString(),
          s.grade,
          gradeValue.toString(),
          qualityPoints.toString()
        ];
      });

    autoTable(doc, {
      startY: 85,
      head: [['Course Name', 'Credits', 'Grade', 'Grade Value', 'Quality Points']],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [74, 124, 89], textColor: 255, fontStyle: 'bold' },
      styles: { fontSize: 10, cellPadding: 3 },
      alternateRowStyles: { fillColor: [240, 245, 241] }, // light green tint
    });

    // Footer
    const finalY = (doc as any).lastAutoTable.finalY || 85;
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text('Generated by GPACal', 14, finalY + 10);

    doc.save(`SGPA_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="bg-gradient-to-br from-rv-green via-rv-green-light to-rv-green-accent p-8 rounded-2xl shadow-2xl text-white relative overflow-hidden"
    >
      <div className="flex flex-col md:flex-row md:items-start justify-between gap-6 mb-8">
        <div className="flex items-center gap-3">
          <div className="p-3 bg-white/20 rounded-xl backdrop-blur-sm shadow-inner">
            <Award size={32} className="text-white" />
          </div>
          <div>
            <h2 className="text-2xl font-display font-bold text-white">Your Results</h2>
            <p className="text-white/90 text-sm font-medium bg-white/10 px-2 py-0.5 rounded-md inline-block mt-1">
              {getPerformanceText(sgpa)}
            </p>
          </div>
        </div>

        <motion.button
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
          onClick={generatePDF}
          className="flex items-center gap-2 px-4 py-2 bg-white text-rv-green font-semibold rounded-lg shadow-lg hover:shadow-xl hover:bg-gray-50 transition-all text-sm group"
        >
          <Download size={18} className="group-hover:-translate-y-0.5 transition-transform" />
          Download Report
        </motion.button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <motion.div
          initial={{ scale: 0.8 }}
          animate={{ scale: 1 }}
          transition={{ delay: 0.1 }}
          className="bg-white/10 backdrop-blur-md rounded-xl p-6 border border-white/20"
        >
          <div className="flex items-center gap-2 mb-2">
            <TrendingUp size={20} className="text-white/80" />
            <span className="text-sm font-body text-white/80">SGPA</span>
          </div>
          <div className={`text-5xl font-display font-black ${getGradeColor(sgpa)}`}>
            {sgpa.toFixed(2)}
          </div>
          <div className="mt-2 text-xs text-white/60">Out of 10.00</div>
        </motion.div>

        <motion.div
          initial={{ scale: 0.8 }}
          animate={{ scale: 1 }}
          transition={{ delay: 0.2 }}
          className="bg-white/10 backdrop-blur-md rounded-xl p-6 border border-white/20"
        >
          <div className="flex items-center gap-2 mb-2">
            <BookOpen size={20} className="text-white/80" />
            <span className="text-sm font-body text-white/80">Total Credits</span>
          </div>
          <div className="text-4xl font-display font-bold">
            {totalCredits.toFixed(1)}
          </div>
          <div className="mt-2 text-xs text-white/60">Credits Earned</div>
        </motion.div>

        <motion.div
          initial={{ scale: 0.8 }}
          animate={{ scale: 1 }}
          transition={{ delay: 0.3 }}
          className="bg-white/10 backdrop-blur-md rounded-xl p-6 border border-white/20"
        >
          <div className="flex items-center gap-2 mb-2">
            <Award size={20} className="text-white/80" />
            <span className="text-sm font-body text-white/80">Quality Points</span>
          </div>
          <div className="text-4xl font-display font-bold">
            {totalQualityPoints.toFixed(2)}
          </div>
          <div className="mt-2 text-xs text-white/60">Total QP Earned</div>
        </motion.div>
      </div>

      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.4 }}
        className="mt-6 p-4 bg-white/10 backdrop-blur-sm rounded-xl border border-white/20"
      >
        <p className="text-sm font-body text-white/90">
          <span className="font-semibold">Formula:</span> SGPA = Total Quality Points ({totalQualityPoints.toFixed(2)}) ÷ Total Credits ({totalCredits.toFixed(1)})
        </p>
      </motion.div>
    </motion.div>
  );
}
